export const polymers = [
  {
    id: 'pebd',
    acronym: 'PEBD',
    name: 'Polietileno de Baixa Densidade',
    rawMaterial: 'Etileno (gás derivado do petróleo).',
    process: 'Polimerização por adição sob alta pressão e temperatura. As moléculas de etileno se unem formando longas cadeias bastante ramificadas.',
    applications: 'Muito usado onde a flexibilidade é essencial: sacolas de supermercado, filmes agrícolas resistentes e plástico bolha.',
    damages: 'Demora centenas de anos para se decompor, fragmenta-se em microplásticos e frequentemente causa asfixia da fauna marinha.',
    products: 'Sacolas plásticas, embalagens flexíveis (arroz, feijão), lonas agrícolas, filmes para revestimento plástico.',
    curiosity: 'É um dos plásticos mais produzidos no mundo devido ao seu baixíssimo custo de produção e alta maleabilidade.',
    color: 'from-blue-400 to-blue-600',
    number: 4,
    image: '/polymers/pebd.png'
  },
  {
    id: 'pead',
    acronym: 'PEAD',
    name: 'Polietileno de Alta Densidade',
    rawMaterial: 'Etileno (gás derivado do petróleo).',
    process: 'Polimerização por adição sob baixa pressão. Forma cadeias muito retas (lineares) que garantem sua rigidez característica.',
    applications: 'Perfeito para resistir a produtos químicos e impactos, usado em frascos de limpeza, higiene e tubulações industriais.',
    damages: 'Seu acúmulo em aterros sanitários e corpos d\'água gera imensa poluição física a longo prazo pela altíssima resistência estrutural.',
    products: 'Embalagens de shampoo, potes duráveis de sorvete, engradados de bebidas, bombonas químicas, tubos de esgoto.',
    curiosity: 'As cadeias poliméricas lineares do PEAD "empacotam" tão perfeitamente que o tornam incrivelmente resistente, sem perder a leveza.',
    color: 'from-cyan-400 to-cyan-600',
    number: 2,
    image: '/polymers/pead.png'
  },
  {
    id: 'pvc',
    acronym: 'PVC',
    name: 'Policloreto de Vinila',
    rawMaterial: 'Cloreto de vinila (derivado de petróleo e gás cloro do sal marinho).',
    process: 'Polimerização por adição onde milhões de monômeros de cloreto de vinila se ligam para formar um material robusto.',
    applications: 'Encanamentos em geral, revestimentos de fios elétricos, fabricação de couro sintético ecológico e esquadrias de janelas.',
    damages: 'Sua incineração (queima) libera dioxinas, gases extremamente tóxicos e cancerígenos. Sua reciclagem é mais complexa.',
    products: 'Canos de água (Tigre/Amanco), cartões de crédito, mangueiras de jardim, LPs (antigos discos de vinil).',
    curiosity: 'O PVC é o único plástico usado em larga escala que não é 100% derivado de combustíveis fósseis (57% vem do sal do oceano).',
    color: 'from-teal-400 to-teal-600',
    number: 3,
    image: '/polymers/pvc.png'
  },
  {
    id: 'pet',
    acronym: 'PET',
    name: 'Polietileno Tereftalato',
    rawMaterial: 'Ácido tereftálico e etilenoglicol (compostos derivados do petróleo).',
    process: 'Polimerização por condensação. Os monômeros reagem expulsando moléculas de água, formando a cadeia do poliéster PET.',
    applications: 'Dominante absoluto em garrafas de bebidas carbonatadas (refrigerantes) por ser impermeável a gases. Também forte em indumentárias.',
    damages: 'Devido ao grande uso descartável (uso-único), gera um volume colossal de lixo e microplásticos nos oceanos mundiais.',
    products: 'Garrafas de água e refrigerante, roupas esportivas (tecidos tipo DRI-FIT de poliéster), vassouras sustentáveis.',
    curiosity: 'É disparado um dos plásticos mais bem-sucedidos em termos de reciclagem em larga escala no Brasil; fios de roupas são frequentemente feitos dele.',
    color: 'from-emerald-400 to-emerald-600',
    number: 1,
    image: '/polymers/pet.png'
  },
  {
    id: 'pp',
    acronym: 'PP',
    name: 'Polipropileno',
    rawMaterial: 'Propileno (gás extraído no refino do petróleo).',
    process: 'Polimerização por adição. Muito parecido com o polietileno, mas utiliza o monômero propileno, suportando temperaturas muito maiores.',
    applications: 'Amplamente usado em recipientes isolantes térmicos, seringas descartáveis (podem ser fervidas/esterilizadas) e tampas duras.',
    damages: 'Como os demais resíduos fósseis, tem acúmulo dramático nos aterros e demora muitos séculos para se degradar na natureza.',
    products: 'Potes "Tupperware" que vão ao micro-ondas, seringas hospitalares, para-choques de automóveis, cadeiras plásticas brancas.',
    curiosity: 'Um superpoder do PP: ele pode ser dobrado milhões de vezes sem romper, motivo pelo qual é a escolha unânime em tampas daquele tipo "flip-top".',
    color: 'from-green-400 to-green-600',
    number: 5,
    image: '/polymers/pp.png'
  },
  {
    id: 'ps',
    acronym: 'PS',
    name: 'Poliestireno',
    rawMaterial: 'Estireno líquido aromático (monômero oriundo do petróleo).',
    process: 'Polimerização por adição. A sua forma amada e expandida, o EPS (isopor), é obtida injetando gases inflamáveis na resina.',
    applications: 'Utilizado desde talheres descartáveis ultra rígidos até o aerado isopor (caixas térmicas) por ser um maravilhoso isolante acústico e térmico.',
    damages: 'Problema gravíssimo em aterros pelo enorme VOLUME inútil que o EPS ocupa. Além de leve, voa com o vento e é perigosamente engolido por tartarugas marinhas.',
    products: 'Bandejas do açougue/frios do supermercado, copos descartáveis térmicos, embalagens protetoras grossas de TVs e eletrodomésticos.',
    curiosity: 'A palavra "Isopor" é na verdade apenas uma marca comercial muito famosa. O nome real da matéria que ele é feito chama EPS, e adivinhe: é composto 98% por AR!',
    color: 'from-indigo-400 to-indigo-600',
    number: 6,
    image: '/polymers/ps.png'
  },
  {
    id: 'pu',
    acronym: 'PU',
    name: 'Poliuretano',
    rawMaterial: 'Reação entre dezenas de diisocianatos e polióis variados.',
    process: 'Polimerização química rápida por condensação resultando num polímero repleto de ligações uretânicas em formato de espuma aerada.',
    applications: 'Rei absoluto nas indústrias de conforto humano (colchões) e limpeza domiciliar (esponjas), além de isolamentos industriais.',
    damages: 'Sua decomposição térmica ou pirólise libera gases terríveis e asfixiantes. A reciclagem desse material por meios mecânicos ainda é rara e custosa.',
    products: 'Espumas fofas de colchão, as clássicas esponjas amarelas de lavar louça de cozinha, estofados de sofás, miolo resistente de pranchas de surfe.',
    curiosity: 'Nos anos 40, sua formulação avançada foi impulsionada na Segunda Guerra Mundial como a única aposta de cientistas desesperados para substituir a borracha.',
    color: 'from-violet-400 to-violet-600',
    number: 7,
    image: 'https://images.unsplash.com/photo-1586282391129-76a6df230234?auto=format&fit=crop&w=800&q=80'
  }
];
